name: hanasu_irc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  characters: ^1.3.0
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.3
  intl: ^0.18.0
  logging: ^1.1.1
  riverpod: ^2.3.2
  test: ^1.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
